# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='time',
        ),
        migrations.AddField(
            model_name='translate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
