# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-12 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
