# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-04 03:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_auto_20180609_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='article_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlepost',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 4, 3, 16, 8, 345000, tzinfo=utc)),
        ),
    ]
