# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-19 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180704_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 7, 5, 53, 180000, tzinfo=utc)),
        ),
    ]
